In [2]:
import gm2
import trfp
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import helper_functions as helper

In [5]:
df = helper.root_to_pandas(run_range=range(3959,3995), prefix='FieldPlainRootOutput_', tr_run=False, sanitize=False)

Reading event 154050/154052 100.00%
loop done: 100%

In [6]:
df.head()

,fp0,fp1,fp2,fp3,fp4,fp5,fp6,fp7,fp8,fp9,...,fp368,fp369,fp370,fp371,fp372,fp373,fp374,fp375,fp376,fp377
1.524384e+09,44817.157394,50136.143085,54504.844966,49222.403486,61605.945836,67063.119021,34869.157832,50681.428771,56152.257043,44691.024146,...,51362.537389,52521.738588,57828.460717,51664.850038,54321.340015,55908.828071,51020.608018,48656.942515,53068.088151,46070.943275
1.524384e+09,44816.853938,50136.383431,54504.871734,49176.101956,61574.863820,67117.067125,34868.284345,50682.467838,56152.199820,44684.773496,...,51362.501926,52521.785844,57829.001270,51666.614852,54334.085875,55908.017306,51021.356877,48656.917248,53065.746047,46073.046312
1.524384e+09,44815.288546,50136.572051,54504.604429,49098.899450,61525.580222,67151.419394,34870.333399,50681.183385,56153.125045,44683.873799,...,51361.449231,52521.958753,57829.079761,51667.993037,54326.310938,55906.935824,51021.172806,48656.815528,53064.956189,46072.599785
1.524384e+09,44813.922889,50136.223303,54505.014676,49179.527267,61548.332509,67109.776990,34866.470079,50680.254950,56152.994008,44679.300728,...,51362.133676,52522.225810,57829.156479,51667.169349,54318.918730,55906.659510,51021.097987,48656.843115,53065.557904,46071.025552
1.524384e+09,44813.705399,50135.951494,54505.467368,49251.639067,61580.041449,67058.274815,34862.033976,50679.834631,56152.290058,44684.240686,...,51364.246277,52522.593730,57829.322258,51662.565411,54321.734465,55908.665549,51022.272515,48657.464883,53069.350810,46070.342466